version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: tf_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - '/var/lib/postgresql/data'
  db-seed:
    build: ./db-seed/
    env_file:
      - .env
    depends_on:
      - postgres
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - '3080:8080'
  task_api:
    build: ./task-api/
    volumes:
      - ./task-api:/usr/app
      - '/usr/app/node_modules'
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db-seed
